'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useEmergencyStore } from '../../store/useEmergencyStore';
import PageTransition from '../../components/layout/PageTransition';
import dynamic from 'next/dynamic';
import { supabase } from '../../lib/supabaseClient';

const PDFButton = dynamic(
  () => import('../../components/reports/PDFButton'),
  { ssr: false, loading: () => <button className="flex-1 h-[var(--spacing-touch-target-min)] flex items-center justify-center gap-2 border-2 border-[var(--color-primary)] text-[var(--color-primary)] rounded-xl font-[family-name:var(--font-label-lg)] text-[length:var(--font-label-lg)]">Preparing PDF...</button> }
);

export default function MedicalSummaryPage() {
  const router = useRouter();
  const { patientDetails, aiResults, emergencyDescription, caseId } = useEmergencyStore();
  const [isClient, setIsClient] = useState(false);
  const [feedback, setFeedback] = useState('');
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false);

  const submitFeedback = async (rating: 'positive' | 'negative') => {
    if (!caseId) return;
    try {
      const payload = {
        patient_case_id: caseId,
        rating: rating,
        feedback: feedback
      };
      console.log("Inserting payload into feedback:", payload);

      const { error } = await supabase.from('feedback').insert([payload]);
      
      if (error) {
        console.error("Supabase Insert Error (feedback):", JSON.stringify(error, null, 2));
        console.error("Error message:", error?.message);
        console.error("Error details:", error?.details);
        console.error("Error hint:", error?.hint);
        console.error("Error code:", error?.code);
      } else {
        console.log('Successfully inserted feedback row.');
        setFeedbackSubmitted(true);
      }
    } catch (err: any) {
      console.error('Unexpected error inserting into feedback:', err?.message || err);
    }
  };

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!aiResults && isClient) {
    router.push('/emergency-description');
    return null;
  }

  return (
    <PageTransition
      backPath="/hospital-finder"
      nextPath="/"
      nextLabel="Finish"
    >
      <main className="flex-grow pt-4 pb-[100px] px-[var(--spacing-margin-mobile)] md:px-[var(--spacing-margin-desktop)] max-w-3xl w-full mx-auto">
        <div className="p-6 space-y-[var(--spacing-stack-lg)] bg-[var(--color-surface)] rounded-3xl shadow-sm border border-[var(--color-outline-variant)]/50">
          
          <div className="text-center mb-6 border-b border-[var(--color-outline-variant)]/50 pb-6">
            <h2 className="font-[family-name:var(--font-headline-lg)] text-[length:var(--font-headline-lg)] text-[var(--color-on-surface)] font-black">Medical Summary</h2>
            <p className="font-[family-name:var(--font-body-md)] text-[length:var(--font-body-md)] text-[var(--color-on-surface-variant)] mt-2">Generated by Emergency Copilot AI</p>
          </div>

          <section>
            <h3 className="font-[family-name:var(--font-label-lg)] text-[length:var(--font-label-lg)] text-[var(--color-primary)] mb-4 flex items-center gap-2 font-bold tracking-wide">
              <span className="material-symbols-outlined text-[20px]">person</span> Patient Demographics
            </h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-[var(--color-surface-container-lowest)] p-4 rounded-2xl border border-[var(--color-outline-variant)]/30 shadow-sm">
                <p className="font-[family-name:var(--font-label-md)] text-[length:var(--font-label-md)] text-[var(--color-on-surface-variant)] font-semibold">Full Name</p>
                <p className="font-[family-name:var(--font-body-lg)] text-[length:var(--font-body-lg)] font-bold text-[var(--color-on-surface)] mt-1">
                  {patientDetails.name || 'Unknown'}
                </p>
              </div>
              <div className="bg-[var(--color-surface-container-lowest)] p-4 rounded-2xl border border-[var(--color-outline-variant)]/30 shadow-sm">
                <p className="font-[family-name:var(--font-label-md)] text-[length:var(--font-label-md)] text-[var(--color-on-surface-variant)] font-semibold">Age</p>
                <p className="font-[family-name:var(--font-body-lg)] text-[length:var(--font-body-lg)] font-bold text-[var(--color-on-surface)] mt-1">
                  {patientDetails.age ? `${patientDetails.age} Years` : 'Unknown'}
                </p>
              </div>
            </div>
          </section>

          <section>
            <h3 className="font-[family-name:var(--font-label-lg)] text-[length:var(--font-label-lg)] text-[var(--color-primary)] mb-4 flex items-center gap-2 font-bold tracking-wide">
              <span className="material-symbols-outlined text-[20px]">vital_signs</span> Reported Emergency
            </h3>
            <div className="flex flex-wrap gap-2">
              <span className="inline-flex items-center gap-1 px-4 py-3 rounded-2xl bg-[var(--color-surface-container-highest)] font-[family-name:var(--font-body-lg)] text-[length:var(--font-body-lg)] text-[var(--color-on-surface)] shadow-sm font-medium">
                {emergencyDescription || 'No details provided'}
              </span>
            </div>
          </section>

          <section>
            <h3 className="font-[family-name:var(--font-label-lg)] text-[length:var(--font-label-lg)] text-[var(--color-primary)] mb-4 flex items-center gap-2 font-bold tracking-wide">
              <span className="material-symbols-outlined text-[20px]">analytics</span> AI Clinical Summary
            </h3>
            <div className="bg-[var(--color-surface-bright)] p-6 rounded-2xl border border-[var(--color-outline-variant)] border-l-4 border-l-[var(--color-primary)] shadow-sm">
              <p className="font-[family-name:var(--font-body-lg)] text-[length:var(--font-body-lg)] text-[var(--color-on-surface)] leading-relaxed">
                {aiResults?.medicalSummary || aiResults?.simpleExplanation}
              </p>
            </div>
          </section>

          <section>
            <h3 className="font-[family-name:var(--font-label-lg)] text-[length:var(--font-label-lg)] text-[var(--color-primary)] mb-4 flex items-center gap-2 font-bold tracking-wide">
              <span className="material-symbols-outlined text-[20px]">medical_services</span> First-Aid Guidance Provided
            </h3>
            <div className="flex flex-col gap-3">
              {aiResults?.nextSteps?.map((step, idx) => (
                <div key={idx} className="flex items-start gap-4 p-4 min-h-[64px] bg-[var(--color-surface-container-lowest)] border border-[var(--color-outline-variant)] rounded-2xl shadow-sm">
                  <div className="flex-shrink-0 w-10 h-10 rounded-full bg-[var(--color-primary-container)] text-[var(--color-on-primary-container)] flex items-center justify-center font-[family-name:var(--font-label-lg)] text-[length:var(--font-label-lg)] font-black">
                    {idx + 1}
                  </div>
                  <div className="pt-1">
                    <h4 className="font-[family-name:var(--font-label-lg)] text-[length:var(--font-label-lg)] text-[var(--color-on-surface)] font-bold">
                      Step {idx + 1}
                    </h4>
                    <p className="font-[family-name:var(--font-body-md)] text-[length:var(--font-body-md)] text-[var(--color-on-surface-variant)] mt-1">
                      {step}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </section>
          
          <section>
            <h3 className="font-[family-name:var(--font-label-lg)] text-[length:var(--font-label-lg)] text-[var(--color-primary)] mb-4 flex items-center gap-2 font-bold tracking-wide">
              <span className="material-symbols-outlined text-[20px]">feedback</span> Provide Feedback
            </h3>
            <div className="bg-[var(--color-surface-container-lowest)] p-4 rounded-2xl border border-[var(--color-outline-variant)]/30 shadow-sm flex flex-col gap-4">
              {!feedbackSubmitted ? (
                <>
                  <textarea 
                    value={feedback} 
                    onChange={(e) => setFeedback(e.target.value)} 
                    placeholder="Any comments on the AI guidance?" 
                    className="w-full bg-[var(--color-surface-bright)] border border-[var(--color-outline-variant)] rounded-xl p-3 text-[var(--color-on-surface)] focus:ring-1 focus:ring-[var(--color-primary)] focus:outline-none"
                    rows={2}
                  />
                  <div className="flex gap-4">
                    <button 
                      onClick={() => submitFeedback('positive')} 
                      className="flex-1 flex items-center justify-center gap-2 h-10 rounded-xl bg-[var(--color-surface-container)] hover:bg-[var(--color-surface-container-high)] border border-[var(--color-outline-variant)]"
                    >
                      <span className="material-symbols-outlined text-green-600">thumb_up</span> Helpful
                    </button>
                    <button 
                      onClick={() => submitFeedback('negative')} 
                      className="flex-1 flex items-center justify-center gap-2 h-10 rounded-xl bg-[var(--color-surface-container)] hover:bg-[var(--color-surface-container-high)] border border-[var(--color-outline-variant)]"
                    >
                      <span className="material-symbols-outlined text-red-600">thumb_down</span> Not Helpful
                    </button>
                  </div>
                </>
              ) : (
                <p className="text-[var(--color-primary)] font-medium text-center">Thank you for your feedback!</p>
              )}
            </div>
          </section>

          <div className="pt-6 border-t border-[var(--color-outline-variant)]/50">
            <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
              <button className="w-full sm:w-auto flex-1 h-[56px] flex items-center justify-center gap-2 bg-[var(--color-primary)] text-[var(--color-on-primary)] rounded-2xl font-[family-name:var(--font-label-lg)] text-[length:var(--font-label-lg)] hover:bg-[var(--color-primary-container)] hover:text-[var(--color-on-primary-container)] transition-colors shadow-sm font-bold tracking-wide">
                <span className="material-symbols-outlined">share</span>
                Share Report
              </button>
              
              <div className="w-full sm:w-auto flex flex-1 items-center gap-4">
                {isClient && aiResults && (
                  <div className="flex-1">
                    <PDFButton patientDetails={patientDetails} aiResults={aiResults} emergencyDescription={emergencyDescription} />
                  </div>
                )}

                <button 
                  aria-label="Print Report" 
                  className="w-[56px] h-[56px] flex items-center justify-center flex-shrink-0 border-2 border-[var(--color-outline-variant)] text-[var(--color-on-surface)] rounded-2xl hover:bg-[var(--color-surface-container-highest)] transition-colors shadow-sm bg-[var(--color-surface-container-lowest)]"
                  onClick={() => window.print()}
                >
                  <span className="material-symbols-outlined">print</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </PageTransition>
  );
}
